### ISSUE TITLE
Entrevista-Irving Fernando Reyes Pacheco 

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-de-irving#2]
[Reporte de entrevista-1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-de-irving/files/9465503/Reporte.de.entrevista-1.pdf)

**Comment by mel-16** [comment]
20% Felicidades

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
